# Generated by Django 3.2.5 on 2022-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booky', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
